<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="FOCUS-QA-10" name="com.focus.testcases.RulesTest" tests="48" failures="7" timestamp="4 Jan 2023 08:04:22 GMT" time="1447.382" errors="0">
  <testcase name="checkPrintPDFFileAfterCreatingHeadeAndFooterLayoutInLedgerReport" time="15.924" classname="com.focus.testcases.RulesTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.RulesTest.checkPrintPDFFileAfterCreatingHeadeAndFooterLayoutInLedgerReport(RulesTest.java:369)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkPrintPDFFileAfterCreatingHeadeAndFooterLayoutInLedgerReport -->
  <testcase name="checkClickOnHiddingOptionInRulesAndClickOnSave" time="27.268" classname="com.focus.testcases.RulesTest"/>
  <testcase name="CheckNavigateToRulesTAB" time="12.426" classname="com.focus.testcases.RulesTest"/>
  <testcase name="checkValidationOFFOrmulaControlAtVoucherLevel" time="22.875" classname="com.focus.testcases.RulesTest"/>
  <testcase name="chekSavingRuleWithBeforeDelete" time="34.302" classname="com.focus.testcases.RulesTest"/>
  <testcase name="checkLOADRuleOptionAtVoucherLevel" time="28.819" classname="com.focus.testcases.RulesTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.RulesTest.checkLOADRuleOptionAtVoucherLevel(RulesTest.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkLOADRuleOptionAtVoucherLevel -->
  <testcase name="checkAddingHeadeAndFooterInLedgerReport" time="47.219" classname="com.focus.testcases.RulesTest"/>
  <testcase name="checkCreatingConditionForRestrictionsWithWarnAndAllowOption" time="25.635" classname="com.focus.testcases.RulesTest"/>
  <testcase name="checkSQLFuntionATExcessStockVoucherLevel" time="24.213" classname="com.focus.testcases.RulesTest"/>
  <testcase name="checkCopyAndPasteWithControlOptionInLedgerReport" time="18.399" classname="com.focus.testcases.RulesTest"/>
  <testcase name="checkAfterEnableHiddenOptionAtVoucherLevel" time="18.919" classname="com.focus.testcases.RulesTest"/>
  <testcase name="checkVoucherLevelOnEnterRuleValidation" time="18.856" classname="com.focus.testcases.RulesTest"/>
  <testcase name="checkItemValuesintoVoucherLevelOnClickOnOkBtnInSearchPopUp" time="4.349" classname="com.focus.testcases.RulesTest"/>
  <testcase name="checkCreatingConditionForRestrictionsWithStopOption" time="28.410" classname="com.focus.testcases.RulesTest"/>
  <testcase name="checkSavingExtraFiledInSalesINvoiceVAT" time="24.571" classname="com.focus.testcases.RulesTest"/>
  <testcase name="checkSavingRulesWithOnLeave" time="77.118" classname="com.focus.testcases.RulesTest"/>
  <testcase name="checkSavingOpeningStockVoucher" time="17.723" classname="com.focus.testcases.RulesTest"/>
  <testcase name="checkCreatingViewOptionInPurchaseVoucher" time="37.762" classname="com.focus.testcases.RulesTest"/>
  <testcase name="checkITEMWithF5Key" time="24.026" classname="com.focus.testcases.RulesTest"/>
  <testcase name="checkSavingPurchaseVoucherVATWithRateBelowAverageRate" time="20.714" classname="com.focus.testcases.RulesTest"/>
  <testcase name="checkViewOptionCreatedInPurchaseVoucherVAT" time="32.742" classname="com.focus.testcases.RulesTest"/>
  <testcase name="checkBodyHeadingColumnWithCustomerAccount" time="14.648" classname="com.focus.testcases.RulesTest"/>
  <testcase name="checkRuleConditionAfterEditingINEnterRule" time="17.256" classname="com.focus.testcases.RulesTest"/>
  <testcase name="checkSavingRuleWithOutInput" time="0.434" classname="com.focus.testcases.RulesTest"/>
  <testcase name="checkEditingAndAddingSavedRuleUnderRecepitsVAT" time="49.254" classname="com.focus.testcases.RulesTest"/>
  <testcase name="chekSavingRuleWithOnEdit" time="50.930" classname="com.focus.testcases.RulesTest"/>
  <testcase name="chekSavingRuleWithOnEnter" time="50.109" classname="com.focus.testcases.RulesTest"/>
  <testcase name="checkSavedRuleWithLoadOptionEnable" time="22.767" classname="com.focus.testcases.RulesTest"/>
  <testcase name="checkAccountTxtWithClickOnF5" time="28.501" classname="com.focus.testcases.RulesTest"/>
  <testcase name="checkEnterF5keyInLedgerReport" time="35.732" classname="com.focus.testcases.RulesTest"/>
  <testcase name="checkValidationOFEditRuleWithWarnAndProcedueInRecepitsVoucher" time="204.752" classname="com.focus.testcases.RulesTest"/>
  <testcase name="checkLoadingAccountValuesFromSearchPopUp" time="2.502" classname="com.focus.testcases.RulesTest"/>
  <testcase name="checkSavingPurchaseVoucherVATWithRateEqualToAverageRate" time="2.825" classname="com.focus.testcases.RulesTest"/>
  <testcase name="checkPrintPDFFileAfterImportingHeaderAndFooterLayoutInStockLedgerReport" time="15.399" classname="com.focus.testcases.RulesTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.RulesTest.checkPrintPDFFileAfterImportingHeaderAndFooterLayoutInStockLedgerReport(RulesTest.java:383)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkPrintPDFFileAfterImportingHeaderAndFooterLayoutInStockLedgerReport -->
  <testcase name="checkChangingDepartmentAsAMERICAAndValidateColounmHeadingName" time="3.450" classname="com.focus.testcases.RulesTest"/>
  <testcase name="checkLogin" time="7.905" classname="com.focus.testcases.RulesTest"/>
  <testcase name="checkStockLedgerReportImportingHeaderAndFooterLayout" time="40.010" classname="com.focus.testcases.RulesTest"/>
  <testcase name="checkSavingPurchaseVoucherVATWithRateBelowAverageRateForWarnAndAllow" time="22.977" classname="com.focus.testcases.RulesTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.RulesTest.checkSavingPurchaseVoucherVATWithRateBelowAverageRateForWarnAndAllow(RulesTest.java:337)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkSavingPurchaseVoucherVATWithRateBelowAverageRateForWarnAndAllow -->
  <testcase name="checkSavingPurchaseVoucherVATWithRateEqualToAverageRateWithWarnAndAllow" time="21.789" classname="com.focus.testcases.RulesTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.RulesTest.checkSavingPurchaseVoucherVATWithRateEqualToAverageRateWithWarnAndAllow(RulesTest.java:344)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkSavingPurchaseVoucherVATWithRateEqualToAverageRateWithWarnAndAllow -->
  <testcase name="checkSavingRuleWithFormulaUnderSalesINvoiceVAT" time="45.043" classname="com.focus.testcases.RulesTest"/>
  <testcase name="checkF5KeyWithRMAPopUpInOpeningStocks" time="29.861" classname="com.focus.testcases.RulesTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.RulesTest.checkF5KeyWithRMAPopUpInOpeningStocks(RulesTest.java:268)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkF5KeyWithRMAPopUpInOpeningStocks -->
  <testcase name="checkF5KeyInFilterPopUpScreen" time="22.584" classname="com.focus.testcases.RulesTest"/>
  <testcase name="checkLoadingFieldsIntoPopOnClickOnRefreshBtn" time="11.896" classname="com.focus.testcases.RulesTest"/>
  <testcase name="checkOnLeaveValiationATVoucherLevelWithDepartmentWales" time="14.853" classname="com.focus.testcases.RulesTest"/>
  <testcase name="checkSavingRulesWithOnLoadOptionEnableInVoucherLevel" time="30.304" classname="com.focus.testcases.RulesTest"/>
  <testcase name="checkSavingPurchaseVoucherVATWithRateGreaterThanAverageRate" time="5.996" classname="com.focus.testcases.RulesTest"/>
  <testcase name="chckRestoreBackUpForSQLFunction" time="111.659" classname="com.focus.testcases.RulesTest"/>
  <testcase name="checkSavingPurchaseVoucherVATWithRateGreaterThanAverageRateWithWarnAndAllow" time="21.676" classname="com.focus.testcases.RulesTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:305)
	at org.testng.Assert.assertEquals(Assert.java:315)
	at com.focus.testcases.RulesTest.checkSavingPurchaseVoucherVATWithRateGreaterThanAverageRateWithWarnAndAllow(RulesTest.java:351)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkSavingPurchaseVoucherVATWithRateGreaterThanAverageRateWithWarnAndAllow -->
</testsuite> <!-- com.focus.testcases.RulesTest -->
